#!/usr/bin/env bash

set -eo pipefail

rootdir="$(dirname $BASH_SOURCE)/.."

source "$rootdir/scripts/utils.sh"

get_base_image() {
  name="${DOCKER_REPO##*/}"
  project="$(get_project "$name")"
  registry="$(get_registry "$project")"
  namespace="$(get_namespace "$project")"

  echo "$registry/$namespace/$name:$DOCKER_TAG"
}

docker build --build-arg BASE_IMAGE="$(get_base_image)" -t $IMAGE_NAME .
